### ISSUE TITLE
Non-standard 'Authorization' schema?

### ISSUE THREAD

**Issue by bmcorser** [wichert/pyramid_jwt#1]
The JWT docs state:
> Whenever the user wants to access a protected route or resource, it should send the JWT, typically in the Authorization header using the Bearer schema. 

We default to __JWT__ as the schema here. Is this a standard somewhere else?

**Comment by bmcorser** [comment]
Great plugin, btw! :+1:

**Comment by wichert** [comment]
I somehow missed this ticket, sorry about that.!

I have seen both `Bearer` and `JWT` being used. The term `typically` on https://jwt.io/introduction/ as you quoted is a really light endorsement, so I am not sure what the best choice really is.

**Comment by bmcorser** [comment]
You're right ... I suppose the `Authorization` schema is somewhat irrelevant to [the JWT standard itself](https://tools.ietf.org/html/rfc7519), where headers are only mentioned in passing.

[All](https://github.com/auth0/angular2-jwt/search?utf8=%E2%9C%93&q=authorization) [Auth0](https://github.com/auth0/angular-jwt/search?utf8=%E2%9C%93&q=authorization) [implementations](https://github.com/auth0/express-jwt/search?utf8=%E2%9C%93&q=authorization) that I glanced at look like they use `Bearer`, whereas [others](https://github.com/themikenicholson/passport-jwt/search?utf8=%E2%9C%93&q=authorization) as you pointed out use `JWT`.

A glance at what is probably [the relevant spec](http://www.ietf.org/rfc/rfc2617.txt) doesn't appear to cover how the `Authorization` header is being used by JWT impls, which leads me to think that perhaps `JWT-Token` might be a better header ...

... since both `http_header` and `auth_type` are easily configurable with `pyramid_jwt`, I'll close this issue!

**Comment by wichert** [comment]
For what it is worth I tend to use a `X-<some name>-API-Key` header for the token.
