### ISSUE TITLE
Using Firebase Auth

### ISSUE THREAD

**Issue by magoarcano** [wichert/pyramid_jwt#11]
Can I combine Firebase Auth with this library?
I'm using Pyramid in App Engine. I've been using traditional Pyramid authentication/authorization. But now I'm trying to authenticate with Firebase Auth.

I can authenticate but I don't find a good way to link it with Pyramid. I'm not sure if It makes sense calling  remember() or forget(), also I don't want to do many redirects with javascript.

Can I link Firebase with Pyramid using pyramid_jwt?

**Comment by wichert** [comment]
I'm afraid I know nothing about firebase, so I can't really help you. [This chapter in their documentation](https://firebase.google.com/docs/auth/admin/#use_a_jwt_library) and [this chapter](https://firebase.google.com/docs/auth/admin/create-custom-tokens) may be useful in figuring this out.
