### ISSUE TITLE
Access & verify token sent in the header

### ISSUE THREAD

**Issue by crooksey** [wichert/pyramid_jwt#13]
I have setup my pyramid app such as:
```
# Enable JWT - JSON Web Token based authentication
config.set_authorization_policy(ACLAuthorizationPolicy())
config.include('pyramid_jwt')
config.set_jwt_authentication_policy('secret200', http_header='Bearer')

# view code:
@view_config(route_name='get_customer_name', request_method='POST', 
	renderer='json_custom')
def get_customer_name(request):
	print (request)
```

My frontend application send a JWT in the header, see the results of print (request) below:

```
'''
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Authorization: Bearer "exJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0ZXN0MiI6Ikx1a2UgQ3Jvb2tzVEVTVDIiLCJpYXQiOjE1MDA0NTM5ODIsInN1YiI6eyJzdG9ja19lbnF1aXJ5X3Blcm0iOnRydWUsIm9yZGVyX2VudHJ5X3Blcm0iOnRydWUsInVzZXJpZCI6NCwidXNlcl9uYW1lIjoibHVrZSIsImFjY291bnRfZW5xdWlyeVwZXJtIjp0cnVlLCJzb2xlbnRfc3RhZmYiOnRydWV9fQ.UwQD6709-4WAidWffhRwaFIBOnXircfL6PC1wg-vpYUJtnojovP_X4QzP6mQDVR4o42vx8FyFpEGh49YJBhteg"
Connection: keep-alive
Content-Length: 21
Content-Type: text/plain
Host: 0.0.0.0:6543
Origin: http://localhost:3000
Referer: http://localhost:3000/order_entry
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/56.0.2924.76 Chrome/56.0.2924.76 Safari/537.36

{"customerid":"7"}
'''
```

You can see that in the header is my JWT token (Authorization: Bearer ).

My question is, in my view code, how do I now access this JWT, I want to verify the signature with the secret key (e.g. secret200) and test the token has not expired, before returning information back to the frontend. I could easily do this manually with the pyJWT library, but I am assuming this plugin is designed to take care of this, could you provide some help/assistance in configuration? Thanks.

**Comment by wichert** [comment]
The library already does that for you, so you do not need to do anything yourself. The only thing you need to do is add an ACL to the pyramid context and set the permission on the view.

**Comment by crooksey** [comment]
I don't see how adding an ACL would do this, as my JWT is not currently available in the request:

```
request.jwt_claims
{}
```

**Comment by wichert** [comment]
Pyramid doesn't trigger any auth-related code unless you add a permission, so that is expected.

**Comment by crooksey** [comment]
Ok so my decoded JWT looks like this:
```
{
  "userid": 4,
  "iat": 1500535681,
  "sub": {
    "order_entry_perm": true,
    "staff": true,
    "userid": 4,
    "stock_enquiry_perm": true,
    "account_enquiry_perm": true,
    "user_name": "luke"
  }
}
```
To which I have added:

```
def add_role_principals(userid, request):
        roles = []
        for item in request.jwt_claims['sub']:
                if item == True:
                        roles.append(item)
        return ['role:%s' % role for role in roles]
```

Then a basic Root ACL for testing
```
class RootACL(object):
    __acl__ = [(Allow, Authenticated, ALL_PERMISSIONS)]

    def __init__(self, request):
        pass
```

Then added a view such as:
```
@view_config(route_name='get_customer_name', request_method='POST', 
	renderer='json_custom', permission="staff")
```
And I constantly get declined views:

```
{"message": "Access was denied to this resource.\n\n\ndebug_authorization of url 

http://0.0.0.0:6543/customerinfo/name.json 
(view name '' against context <backend_ecom2.security.RootACL object at 0x7f59d9b0ac50>): 
ACLDenied permission 'staff' via ACE '<default deny>' in 
ACL [('Allow', 'system.Authenticated', <pyramid.security.AllPermissionsList object at 0x7f59e5edef98>)] 
on context <backend_ecom2.security.RootACL object at 0x7f59d9b0ac50> 
for principals ['system.Everyone']\n\n", "code": "403 Forbidden", "title": "Forbidden"}
```

I don't think my jwt is being authenticated, hence the deny errors, have I missed anything else?

**Comment by wichert** [comment]
That looks like 1) JWT is decoded correctly, 2) ACL is picked up correctly and 3) the right permission is checked. However your `add_role_principals` function is not used. How did you hook that up?

**Comment by crooksey** [comment]
In: https://github.com/wichert/pyramid_jwt/blob/master/src/pyramid_jwt/policy.py#L61

If I try and do that manually with the same information I pass to the pyramid-jwt configuration, e.g.
```
token = request.headers.get('Authorization: Bearer')
```
or:
```
token = request.headers.get('Bearer')
```
Both result as None, however if I do:

```
token = request.headers.get('Authorization')
```
I get the right information (but with the prefix of 'Bearer':
```
Bearer "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyaWQiOjQsImlhdCI6MTUwMDUzNTY4MSwic3ViIjp7Im9yZGVyX2VudHJ5X3Blcm0iOnRydWUsInNvbGVudF9zdGFmZiI6dHJ1ZSwidXNlcmlkIjo0LCJzdG9ja19lbnF1aXJ5X3Blcm0iOnRydWUsImFjY291bnRfZW5xdWlyeV9wZXJtIjp0cnVlLCJ1c2VyX25hbWUiOiJsdWtlIn19.VHoqrQ3ngdEgswC_BpF-85SCqeOdic_i7ywUmmqBBREqYXcU9yTNMg1GfL5iUQEb2g3xFg0gTfYw90NHosrQA"
```
But still not authenticating, am I dealing with the header prefix correctly?

**Comment by crooksey** [comment]
Hooked up with:
```
config.set_jwt_authentication_policy('secret200', http_header='Authorization', 
                                                callback=add_role_principals)
```

**Comment by wichert** [comment]
Try sticking an `import pdb ; pdb.set_trace()` in `add_role_principals` to see if it is called?

**Comment by crooksey** [comment]
No, its not, here is an overview of my settings:

```
def add_role_principals(userid, request):
        roles = []
        import pdb ; pdb.set_trace()
        for item in request.jwt_claims['sub']:
                if item == True:
                        roles.append(item)
        return ['role:%s' % role for role in roles]

def main(global_config, **settings):
        """ This function returns a Pyramid WSGI application.
        """
        config = Configurator(settings=settings,  root_factory='.security.RootACL')
        config.include('.cors')
        config.add_cors_preflight_handler()

        # Enable JWT - JSON Web Token based authentication
        config.set_authorization_policy(ACLAuthorizationPolicy())
        config.include('pyramid_jwt')
        config.set_jwt_authentication_policy('secret200', http_header='Authorization', 
                                                callback=add_role_principals)
        

        # configure custom JSON renderers 
        json_renderer = JSON()
        json_renderer.add_adapter(datetime.date, datetime_adapter)
        json_renderer.add_adapter(Decimal, decimal_adapter)
        config.add_renderer('json_custom', json_renderer)
        # Load model files
        config.include('.models')

        # Customer Info JSON
        config.add_route('get_customer_name', '/customerinfo/name.json')

        config.scan()
        return config.make_wsgi_app()
```

**Comment by wichert** [comment]
We've resolved this on irc. This was due to several issues:

* not using the `http_header` and `auth_type` parameters for `set_jwt_authentication_policy` correctly.
* Passing a dictionary instead of a string or integer as principal to `create_jwt_token`

**Comment by hamzamensi** [comment]
i have the same problem , i get the token perfectly but not jwt_claims 
token
('Bearer', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNoX2FjY291bnRfaWQiOiJjR0lWMlZaWmZncSQ2cnlOZ0wzUkdBPT0iLCJfZl8iOlsiTG9nZ2VkIGluIHN1Y2Nlc3NmdWxseS4iXSwiaWRfdmlydHVhbCI6IjZ0b0VvTmhSM2IiLCJhdXRoLnVzZXJpZCI6InB1bnRvYXp6dXJyb0BkY3BhcnRuZXJzLmZyIiwidXNlciI6eyJhY2NvdW50X2lkIjo3MTYwLCJkZWZhdWx0X2xhbmd1YWdlIjoiZnIiLCJtZW1iZXJPZiI6WyJ0ZWNobmljYWwiXSwiZGVmYXVsdF9jdXJyZW5jeV9pZCI6IkVVUiIsInVzZXJIYW5kbGVyIjoiVXNlcnMiLCJsb2dpbiI6InB1bnRvYXp6dXJyb0BkY3BhcnRuZXJzLmZyIiwibmFtZSI6IlB1bnRvIEF6enVybyAtIERLQiJ9LCJjcmVkZW50aWFscyI6eyJncm91cF9pZCI6MiwibmV0ZXZlbl9sb2dpbl9lbmFibGVkIjp0cnVlfX0.kJ5pRUnjhV8It5c1sPUn-53ZK_HIAD8mZbn3TK_N0Hw')
jwt_claims
None
init.py : 
config.include('pyramid_jwt')
    # FixeMe
    config.set_jwt_authentication_policy('secret',callback=add_role_principals)
    config.set_authorization_policy(ACLAuthorizationPolicy())
in my view : 
tokenSession =  request.create_jwt_token(1,datauser=datauser,permissions=permissions)

i have put ipdb in my call back but it is not called 

how can i fix that issue please ?

**Comment by wichert** [comment]
@hamzamensi That token seems to be something quite unrelated to your code. It decodes to this:

```
{u'_f_': [u'Logged in successfully.'],
 u'auth.userid': u'puntoazzurro@dcpartners.fr',
 u'credentials': {u'group_id': 2, u'neteven_login_enabled': True},
 u'hash_account_id': u'cGIV2VZZfgq$6ryNgL3RGA==',
 u'id_virtual': u'6toEoNhR3b',
 u'user': {u'account_id': 7160,
           u'default_currency_id': u'EUR',
           u'default_language': u'fr',
           u'login': u'puntoazzurro@dcpartners.fr',
           u'memberOf': [u'technical'],
           u'name': u'Punto Azzuro - DKB',
           u'userHandler': u'Users'}}
```

Which does not look like anything JWT to me: there is no `sub` key with the principal and no `iat` key with token generation timestamp. I don't know how you generated that token, but it does not look like anything pyramid_jwt will generate.

**Comment by einarjohnson** [comment]
Hi guys,
I am wondering if there are any concrete samples out there that outline how I secure a REST API using bearer tokens?

**Comment by crooksey** [comment]
@einarjohnson yes, let me see if I can knock up a quick example

**Comment by crooksey** [comment]
@einarjohnson  take a look at this, hope it helps:

https://github.com/crooksey/pyramid_jwt/blob/master/docs/example.md

**Comment by einarjohnson** [comment]
thank  you very much for this, will take a look!

**Comment by crooksey** [comment]
@einarjohnson i have jumped on #pyramid on freenode if you want anymore help.

**Comment by einarjohnson** [comment]
works like a charm,

however, when I try to use a token from https://demo.identityserver.io/ I get an error:
[pyramid_jwt:67][waitress] Invalid JWT token from ::1: Algorithm not supported

The header from the token is
{
  "alg": "RS256",
  "kid": "b83451c57f67fdf5224f9fd0b78b81a3",
  "typ": "JWT"
}
Is this encryption mechanism not supported?

**Comment by wichert** [comment]
PyJWT only supports the RS256 algorithm if you have the [cryptography package](https://pypi.org/project/cryptography/) installed.

**Comment by einarjohnson** [comment]
many thanks for this, i get a bit further now. i now get errors that the public key cannot be loaded to verify the signature. should I be using the public key from the https://demo.identityserver.io endpoint when initializing the authentication policy with set_jwt_authentication_policy ?
