### ISSUE TITLE
Simpler integration with pyramid_authstack

### ISSUE THREAD

**Issue by aysonje** [wichert/pyramid_jwt#16]
I recently stumbled upon this repo (thanks!) and [pyramid_authstack](https://github.com/wichert/pyramid_authstack) (thanks again!). Unfortunately, adding the `JWTAuthenticationPolicy` is not as simple as

```
    jwt_policy = JWTAuthenticationPolicy(...)
    authn_policy = AuthenticationStackPolicy()
    authn_policy.add_policy('key', jwt_policy)
    config.set_authentication_policy(authn_policy)
    ...
```
When done that way, one still needs to manually add
```
    config.add_request_method(request_create_token, 'create_jwt_token')
    config.add_request_method(request_claims, 'jwt_claims', reify=True)
```
I think it would be nice if the second block of code can be done automatically or handled gracefully inside `JWTAuthenticationPolicy`

**Comment by wichert** [comment]
I don't see how that can work. JWTAuthenticationPolicy is just an [IAuthenticationPolicy](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.IAuthenticationPolicy) implementation, and as such it can not do anything else like adding request methods.

pyramid_authstack is a very rare thing to use, and I'm not quite convinced that it makes sense to add special support functions for it here or in other places. For what it's worth if you want to reuse a much logic from `set_jwt_authentication_policy()` you can do something like this:

```python
from pyramid_jwt import set_jwt_authentication_policy

class MagicConfig:
    def __init__(self, config, authstack_policy, key):
        self.config = config
        self.authstack_policy = authstack_policy
        self.key = key

    def get_settings(self):
        return self.config.get_settings()

    def set_authentication_policy(self, policy):
       self.authstack_policy(self.key, policy)

    def add_request_method(self, callable, name, reify=False):
         self.config.add_request_method(callable, name, reify= reify):

authn_policy = AuthenticationStackPolicy()
set_jwt_authentication_policy(MagicConfig(authn_policy, 'key'), …)
```

but as you can see that is already more complicated than wat you are doing.
