### ISSUE TITLE
Support for additional claims in create_jwt_token method

### ISSUE THREAD

**Issue by bfin** [wichert/pyramid_jwt#2]
First, thanks for publishing this package. Like you, I was using [pyramid_jwtauth](https://github.com/ajkavanagh/pyramid_jwtauth). This is a much cleaner implementation!

I need to include additional claims (e.g. group, role) in the payload, which ideally I'd like to be able to include like...

```python
token = request.create_jwt_token(claims)
```

...instead of having to define an additional method...

```python
import jwt
from pyramid.interfaces import IAuthenticationPolicy

def encode_auth_token(request, claims):
    policy = request.registry.queryUtility(IAuthenticationPolicy)
    return jwt.encode(claims, policy.private_key, algorithm=policy.algorithm)

token = encode_auth_token(request, claims)
```

(Of course, this doesn't include any default claims like your current `create_jwt_token` method.)

I'd suggest that additional claims are common enough to warrant including in the convenience method attached to the request object. If I submitted a PR, would you rather see the inclusion of additional claims as an update to the `create_jwt_token` method or as a new method altogether (e.g. `create_custom_jwt_token`)? If an update to `create_jwt_token` is preferable, could it be a breaking change like...

```python
token = request.create_jwt_token(claims)
```

...or should it be a non-breaking (but more confusing) change like...

```python
token = request.create_jwt_token(user_id, claims)
```
?

Thanks.

**Comment by wichert** [comment]
I think it has to be a non-breaking change, but for another reason: pyramid_jwt uses the principal as `sub` (subject) claim, of which there can be only one. To me that still feels like the most natural thing to do. I do agree that we should support other claims as well, and your suggestion would be my preferred option:

```python
def create_jwt_token(sub, **claims):
    """Create a JWT token.

   The principal is used as the `sub` claim in the generated token. You can specify extra claims
    (both public and private) by specifying extra keyword parameters.

    >>> token = request.create_jwt_token(user.id, 
        name=user.name, 
        admin=(user.role == 'admin'))
```

That is the easy part. The harder part of the API is how to expose claims. Perhaps should should be a property on the request? For example:

```python
user_id = request.authenticated_userid  # Use normal pyramid auth policy API
admin = request.jwt_token.get('admin')  # Directly expose the JWT claims as a property?
```

**Comment by wichert** [comment]
I have added support for extra claims in the 1.1 release.
