### ISSUE TITLE
Wrong prefix for algorithm check when public key is present

### ISSUE THREAD

**Issue by m1schka** [wichert/pyramid_jwt#20]
hey,

took me a while to figure out but you're checking the wrong prefix when using an asymetric ES algorithm. According to [PyJWT documentation](https://github.com/jpadilla/pyjwt/blob/a1205186d7a4f9689b6b2efcd93bae89324a5841/docs/algorithms.rst), the prefix is `ES` and not [`EC`](https://github.com/wichert/pyramid_jwt/blob/69f51ae9a4e17a647e1a91cd0123efa79c46512f/src/pyramid_jwt/__init__.py#L17).
For me, this resulted in not loading the public key (being None).

Should be an easy fix for you.
Thx

**Comment by wichert** [comment]
More generally perhaps everything that is not a HMAC is public-key, so the right test is probably `if not algorithm.startswith('HS')`.

**Comment by wichert** [comment]
This change is in the new 1.3 release.

**Comment by m1schka** [comment]
blazing fast, thx!
