### ISSUE TITLE
Catch `jwt.InvalidTokenError` exception

### ISSUE THREAD

**Issue by Mukhametvaleev** [wichert/pyramid_jwt#32]
Hello! I want to catch `jwt.InvalidTokenError` exception with my pyramid app to return a correct `401` status code. How i can implement that?

**Source code:**
https://github.com/wichert/pyramid_jwt/blob/master/src/pyramid_jwt/policy.py#L76t

**Comment by wichert** [comment]
There is no need to do that. You can just use normal Pyramid authorization logic to generate a 401 result on authorization failures.
