### ISSUE TITLE
Log string formatted

### ISSUE THREAD

**Issue by TomOudeNijhuis** [wichert/pyramid_jwt#33]
The params of log string in src/pyramid_jwt/policy.py line 77 are not formatted. It shows up as following in my logfile:
> Invalid JWT token from %s: %s

I am using python version 3.6.9. 
Is it because of the way I initialize the logger or could it be a pyramid_jwt issue?

**Comment by wichert** [comment]
This looks like a strange logger configuration issue. The logger is definitely supposed to format the string correctly. Here is a quick example:

```python
>>> import logging
>>> logging.basicConfig()
>>> log = logging.getLogger('pyramid_jwt')
>>> log.warning("Invalid JWT token from %s: %s", '1.2.3.4', 'error')
WARNING:pyramid_jwt:Invalid JWT token from 1.2.3.4: error
```
 Perhaps you use a formatter that does not do that correctly?

**Comment by Tom-AEMICS** [comment]
Forgot about this issue. You were right my logger settings were incorrect.

**Comment by TomOudeNijhuis** [comment]
Forgot about this issue. You were right my logger settings were incorrect.

**Comment by TomOudeNijhuis** [comment]
Forgot about this issue. You were right my logger settings were incorrect.
