### ISSUE TITLE
Expired token allowed to access views.

### ISSUE THREAD

**Issue by crooksey** [wichert/pyramid_jwt#34]
I may be having a blank moment here, but I thought if a token was invalid/expired, it would not allow the request to retrieve view data that was protected with a permissions= flag.

For example:

```
@view_config(route_name='add_product', request_method='POST',
             renderer='json', permission="website_staff")
```

I can see that my console is logging an expired token, judging by 

https://github.com/wichert/pyramid_jwt/blob/3390d98d361568d6a2e04f5c786b6ec8ddb84a2d/src/pyramid_jwt/policy.py#L78

That pyramid_jwt is returning {} (have tested this locally and this is the case) yet the request is still able to access a protected view. Shouldn't this throw a forbidden error?

For example:
```
import pyramid.httpexceptions as exc
...
raise exc.HTTPForbidden()
```

However, if I try and access a protected view, with no token, a 403 does get returned, so I am unsure why when returning {} after warning that the token is expired, is still returning data.

**Comment by wichert** [comment]
I suppose that depends on your authorization policy. The logic here is:

1. Pyramid calls `JWTAuthenticationPolicy.unauthenticated_userid(request)`, via `CallbackAuthenticationPolicy.effective_principals()`
2. This uses `request.jwt_claims`, which is a request property implemented by `JWTAuthenticationPolicy.get_claims()`
3. `get_claims()` returns an empty dictionary as you found
4. this results in `JWTAuthenticationPolicy.unauthenticated_userid()` returning None
5. this results in CallbackAuthenticationPolicy.effective_principals returning `[Everyone]`

After that it depends on your authorization policy - that tells Pyramid wether to invoke your view or return an error. Have you tried enabled [authorization debug logging](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html#debugging-authorization) to see what is happening?

**Comment by crooksey** [comment]
Wiggy, I am so sorry, I have a very large ACL and I forgot i had allow EVERYONE, ALL PERMISSIONS.  Removing obviously made it function as expected, sorry for the red herring.

**Comment by wichert** [comment]
No worries 😄
