### ISSUE TITLE
Is there any plan to add graphene/graghql support to pyramid_jwt?

### ISSUE THREAD

**Issue by sydoluciani** [wichert/pyramid_jwt#37]
@wichert  

Is there any plan to add graphene/graghql support to pyramid_jwt?

There is already Django and Flask version of such application,
that support both graphene and jwt, but nothing in Pyramid yet.

Thanks

**Comment by wichert** [comment]
I'm afraid I have no idea what that would mean?

**Comment by sydoluciani** [comment]
Sorry for not being clear.

Here is the tutorial to implement Graphql in Python:
https://www.howtographql.com/graphql-python/4-authentication/

Tutorial is using Django and Django-graphql-jwt for authentication:
https://github.com/flavors/django-graphql-jwt

Flask-JWT-Extended is closest implementation to Pyramid_JWT:
https://github.com/vimalloc/flask-jwt-extended/tree/master/flask_jwt_extended

And here is some example of implementation:
https://github.com/flavors/django-graphql-jwt/issues/6

**
> pyramid_jwt has request.create_jwt_token(user_id) to create the token, but > request_create_token is not accessible outside of request, as well couldn't  > find the verification token, refresh token or invalidate token 
> in pyramid_jwt.
**

Thanks


Thank you

**Comment by phrfpeixoto** [comment]
The JWT specification does not provide neither verification nor refresh tokens. Token invalidation is a limitation for JWT Tokens and cannot be done. Flask-JWT-Extended is, as its name say, extends upon it.

That being said, implementing refresh tokens here would be great.

**Comment by wichert** [comment]
I would happily look at a PR to add new features such as refresh tokens. I don't have any plans to add any GraphQL specific logic to pyramid_jwt.
