### ISSUE TITLE
Invalid json_encoder on master branch

### ISSUE THREAD

**Issue by phrfpeixoto** [wichert/pyramid_jwt#39]
Hi there,

The master branch is failing tests due to the incorrectly set `json_encoder` default.
PR #12 introduced Pyramid's `json_renderer_factory` as a default value for the `json_encoder` parameter to be used by `jwt`.

`json_renderer_factory` is **not** an encoder. It's a factory pattern, that creates a Pyramid Renderer. These are completely different objects, that have completely different interfaces. The renderer itself has it's own JSON serializer and extends on it using Pyramid's adapters.

The renderer generated by this factory is **not** a subclass of `JSONEncoder`

I guess the goal here would be to benefit from any configured JSON renderer adapter. If so, we should properly generate a `default` function to be used by the `JSONEncoder`, like `json_renderer_factory` does on-demand.

**Comment by phrfpeixoto** [comment]
I've looked further into this, and I see a few problems:

Pyramid's documentation for adding adapters suggest that the user [should replace the original adapter](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/renderers.html#using-the-add-adapter-method-of-a-custom-json-renderer):
```python
from pyramid.renderers import JSON

if __name__ == '__main__':
    config = Configurator()
    json_renderer = JSON()
    def datetime_adapter(obj, request):
        return obj.isoformat()
    json_renderer.add_adapter(datetime.datetime, datetime_adapter)
    config.add_renderer('json', json_renderer)
```
Internally, these adapters are used as the `default` parameter on the `json.dumps` function.

It seemed simple enough: All we had to do is get the default json renderer (`json_renderer_factory`) and use it's adapters on our own encoder, and here's come the first point of confusion: `json_renderer_factory` is a global variable within the the `pyramid.renderers` package, meaning that this code also works:

```python
from pyramid.renderers import json_renderer_factory

if __name__ == '__main__':
    config = Configurator()
    def datetime_adapter(obj, request):
        return obj.isoformat()
    json_renderer_factory.add_adapter(datetime.datetime, datetime_adapter)
```

And this is where the issue rises: Should we look at the adapters on global `json_renderer_factory`? Or on whatever json rendered has been `config.add_renderer`'ed by the user (which might be a completely different class)?

**Comment by phrfpeixoto** [comment]
IMO, the correct implementation seems to be querying the Pyramid registry and looking for the currently registered json renderer, but this leaves a loophole for situations like this:

```python
 from pyramid.renderers import JSON, json_renderer_factory

class MyClass():
    pass

if __name__ == '__main__':
    config = Configurator()

    # Define a new renderer and add an adapter to it
    json_renderer = JSON()
    def datetime_adapter(obj, request):
        return obj.isoformat()
    json_renderer.add_adapter(datetime.datetime, datetime_adapter)

    # Define the new adapter as the default 'json' renderer
    config.add_renderer('json', json_renderer)

    # Later in the game define another adapter on the global json_renderer_factory, which is no longer used
    json_renderer_factory.add_adapter(MyClass, lambda obj, req: return obj.__class__.__name__)
```

That `json_renderer_factory` is no longer used, so that adapter will never be used, not in Pyramid renderers, nor on our custom `JSONEncoder`

**Comment by phrfpeixoto** [comment]
On top of this there is also a possibility that the user defines a completely new json renderer and register is to Pyramid using a different renderer id:

```python
from pyramid.renderers import JSON

if __name__ == '__main__':
    config = Configurator()
    json_renderer = JSON()
    def datetime_adapter(obj, request):
        return obj.isoformat()
    json_renderer.add_adapter(datetime.datetime, datetime_adapter)
    config.add_renderer('custom_json', json_renderer)
```

In that case, all the user-defined adapters will be set on that custom renderer, and this lib would never benefit from it.

It seems to me that this is becoming out of the scope of `pyramid_jwt` lib. This should simply allow use user to use a custom encoder, as it already did.

**Comment by phrfpeixoto** [comment]
I'd welcome any comments from @wichert and @julienmeyer

**Comment by phrfpeixoto** [comment]
I've submitted a PR reverting #12, but if you are interested I have a code ready that queries for the currently set json renderer within Pyramid and uses its adapters.

**Comment by wichert** [comment]
@phrfpeixoto I am a little bit confused here. You said that the tests are failing, but they all seem to be passing as far as I can see? For example the [most recent CI run](https://github.com/wichert/pyramid_jwt/actions/runs/63092096) had not problems.

**Comment by wichert** [comment]
There seem to be a few approaches here:

1. have nothing configurable, and just use the standard library's behaviour. This was the situation before #10, and #12. Downside is that we can not support things like uuids.
2. always use the current json renderer from Pyramid. This allows people to add support for other types through a standard Pyramid interface.
3. make the JSON encoder configurable. This was the situation after #10.
4. make the JSON encoder configurable, and default to using an instance of `pyramid.renderers.JSON`. This is the current situation

It seems that current situation is possible the most unintuitive options. Option 3 is probably the most intuitive. @phrfpeixoto, I'm guessing that is the code that you have ready? I would love to look at a PR with those changes.

**Comment by phrfpeixoto** [comment]
> @phrfpeixoto I am a little bit confused here. You said that the tests are failing, but they all seem to be passing as far as I can see? For example the [most recent CI run](https://github.com/wichert/pyramid_jwt/actions/runs/63092096) had not problems.

That CI run is for commit [685da35](https://github.com/wichert/pyramid_jwt/commit/685da3535a5370ddbd76a8a79f3826e723e466ce). The breaking changes were on the merge on #12 [8f1326](https://github.com/wichert/pyramid_jwt/commit/8f1326accdd57a3bf129d35f047eb4b623905ad7)

I simply cloned the repo, switched to master, and ran the tests. It breaks.

**Comment by phrfpeixoto** [comment]
Both option 1 and 2 seems poor choices for me, as it does not allow for configurability.

Option 3 seems a perfectly good solution and it's the one I had in production.

Option 4 is exactly what is causing this trouble: It defaults to a JSON Renderer, which is not an subclass of `JSONEncoder` and uses a different API.

**Comment by wichert** [comment]
I've merged your PR on master.

**Comment by phrfpeixoto** [comment]
Thanks! I'll submit the new one as soon as I'm done with work.
