### ISSUE TITLE
Use Pyramid's default JSON Encoder

### ISSUE THREAD

**Issue by phrfpeixoto** [wichert/pyramid_jwt#41]
As discussed on #40, I'm proposing a change for using Pyramid's default json encoder on this lib

**Comment by phrfpeixoto** [comment]
Basically, what I'm doing here is injecting the Pyramid Configurator's registry within our custom encoder factory.

With that at hand, the factory can query for the the framework's default JSON renderer and use its adapter as required.

**Comment by wichert** [comment]
Thanks! I've merged that and made a new release.
