### ISSUE TITLE
Principals are "exploded" when added to effective_principals

### ISSUE THREAD

**Issue by chronosx7** [wichert/pyramid_jwt#44]
I'm combining pyramid's authorization tutorial with pyramid_jwt docs and after configuring **set_jwt_authentication_policy** a simple callback:

![imagen](https://user-images.githubusercontent.com/7991472/92680711-33e66a00-f2f1-11ea-8a43-ca445f67e5da.png)

It appears as exploded in the effective_principals dictionary, preventing the user from being identified

![imagen](https://user-images.githubusercontent.com/7991472/92680820-7c9e2300-f2f1-11ea-8c44-a9c8d08288ab.png)

When I log jwt_claims it appears as "manager" but somehow gets exploded afterwards.

**Comment by wichert** [comment]
This does not look like a bug. `request.jwt_claims` is a dictionary that contains all the claims from the JWT. What value they have is entirely up to the entity that is creating the JWT. I am guessing in your case the `roles` claim is a string, and not a list of strings. In other words I suspect you are doing this:

```python
token = request.create_jwt_token(user_id, roles='manager')
```

There are two ways to fix your code. You can either change how you generate the JWT to use a list of the `roles` claim:

```python
token = request.create_jwt_token(user_id, roles=['manager'])
```

Or you can convert it to a list in your `add_role_principals` method:

```python
def add_role_principals(userid, request):
    return [request.jwt_claims['roles']]
```
